### ISSUE TITLE
Ponctuations doubles

### ISSUE THREAD

**Issue by krop** [krop/Oxygen-Not-Included_french#3]
Dans beaucoup de pays francophones, les ponctuations doubles sont précédées et suivies d'une espace. Que faire dans la traduction ?

Avis bienvenus

**Comment by VonOx** [comment]
Espace après la ponctuation mais pas avant

**Comment by krop** [comment]
Parfait, c'est réglé alors. Je pense avoir tout uniformisé déjà.
