### ISSUE TITLE
Traduction de "tile"

### ISSUE THREAD

**Issue by krop** [krop/Oxygen-Not-Included_french#4]
Plusieurs traductions sont utilisées et peuvent être unifiées :
- Dalle
- Plancher
- Carrelage

le terme "Dalle" me semble plus approprié, carrelage fait penser à la faïence, plancher fait penser au bois.

**Comment by VonOx** [comment]
+1 pour dalle

**Comment by BuBuaBu** [comment]
tuile ?

**Comment by krop** [comment]
et tuile nous faisait penser à la couverture. On va prendre dalle qui est finalement plutôt neutre comparé aux autres (les modifs seront faite ce week end)

**Comment by krop** [comment]
Pour reprendre le contexte, tile désigne tout ce qu'on peut mettre au sol mais aussi tout ce qui fait office de cloison.

**Comment by krop** [comment]
Corrigé
