### ISSUE TITLE
Meal Lice

### ISSUE THREAD

**Issue by krop** [krop/Oxygen-Not-Included_french#6]
Il n'est sans doute pas question d'un pou. Dans les autres messages, il est question d'une céréale et d'un pain compact réalisé à partir de cet ingrédient.

**Comment by BuBuaBu** [comment]
Sur le wiki gamepedia : https://oxygennotincluded.gamepedia.com/Meal_Lice
"A flavorless grain that almost never wiggles on its own."

Par contre vu que c'est produit dans le "microbe musher", la traduction par poux est assez logique.

**Comment by krop** [comment]
Bon, va pour les poux. Ils poussent sur le mealwood (décrits comme des trucs qui gigotent) et sont transformés en liceloaf, que je vais traduire en morceau de poux pour garder l'idée d'une nourriture peu attirante.

Merci.

**Comment by krop** [comment]
Comme j'ai encore un doute, j'ai ouvert un post sur le forum officiel pour avoir un retour. Mon problème vient de "Meal" qui peut être traduit dans certains cas par "farine" http://www.wordreference.com/enfr/meal qui correspondrait aussi à la description "an oddly wriggly grain"

**Comment by krop** [comment]
Le sujet sur le forum donne des pistes intéressantes https://forums.kleientertainment.com/topic/86166-food-translations/ 
Faut imaginer des points communs entre le Meal Lice et le le Meal Worm (https://en.wikipedia.org/wiki/Mealworm)

Des poux de farine pour faire écho au ver de farine ?

**Comment by krop** [comment]
La Traduction est faite (commit 1192d12)
Mealwoods  → Arbre à Poux
Meal Lice → larves de farine (pour coller à l'animation en jeu et la description qui en est faite en VO.
LiceLoaf -> Pain de Larves
